### ISSUE TITLE
Support for input sizes i.e form-select-sm

### ISSUE THREAD

**Issue by prionkor** [apalfrey/select2-bootstrap-5-theme#37]
Currently, the theme doesn't support small size (`sm`). It falls back to default size. 

Here is a codepen for testing https://codepen.io/prionkor/pen/vYxdZeK

**Comment by apalfrey** [comment]
Small and large sizes are supported, just not in the conventional way that Bootstrap does it at the moment.

Here's how you can set your select size to small:
```
$("select").select2({
    theme: "bootstrap-5",
    containerCssClass: "select2--small", // For Select2 v4.0
    selectionCssClass: "select2--small", // For Select2 v4.1
    dropdownCssClass: "select2--small",
});
```

The main reason we're currently doing it like this is because of how Select2 works, with the dropdown at the bottom of the page by default.

However, this has always bugged me so I am trying to figure out a better solution to this where users can just use either `.form-select-sm` or `.form-select-lg`.

This is what I've got so far: https://codepen.io/apalfrey/pen/YzZaWVP I'm going to be continuing testing this, debugging it and trying to come up with any other solutions, but if anyone has any suggestions, please let me know!
