### ISSUE TITLE
Search field not focused

### ISSUE THREAD

**Issue by stojanvujkov** [apalfrey/select2-bootstrap-5-theme#38]
Using latest versions of bootstrap5, jquery and select2, theme does not focus on the search field when dropdown opens. See attachment.
[index.txt](https://github.com/apalfrey/select2-bootstrap-5-theme/files/6612225/index.txt)

**Comment by apalfrey** [comment]
Looks like this is a known issue in Select2: select2/select2#5993

As this is just a theme which is purely CSS, there's nothing we're able to do to fix this and you'll have to refer to there. However, I did do some testing and there are some ways to fix this;

Downgrading to jQuery 3.5.1 doesn't have this issue as seen here: https://codepen.io/apalfrey/pen/yLMERBw

Also, there is a fix in the issue I linked above (found here: https://github.com/select2/select2/issues/5993#issuecomment-848850846). I've tried that out and it does seem to work just fine with jQuery 3.6.0 and the code you supplied as seen here: https://codepen.io/apalfrey/pen/LYWrgGb

Sorry we couldn't be of more help as the issue seems to be on Select2/jQuery's side, but I hope this has helped you get that sorted out!
